image: ruby:2.5.3

cache:
 paths:
   - vendor/bundle

services:
 - postgres:latest

variables:
 # BUNDLE_PATH: vendor/bundle
 # DISABLE_SPRING: 1
 

before_script:
 # Project setup


stages:
 - test1
 

Tests1:
 stage: test1
 script:
   - bundle exec rubocop 

